POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmtvMTIzIiwiaWQiOiI2Mjk5ODNhZmJiNzNlZTNlNGY4ZmU5NGMiLCJpYXQiOjE2NTQyMzA4NzF9.cYxTjnKARaSNTCxXbAjYT8Pzb53-D_ghAMtd-WWYmxA

{
    "title": "Tarinat",
    "author": "Martti",
    "url": "https://google.com",
    "likes": 98
    
}